# headers and icon 
title: Zhiling Chen
info: ME @ UCONN
icon-pic: assets/img/batman_icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
